const ERROR_CODE = 500;
const ERROR_CODE_UNDEFINED = 404;
const ERROR_CODE_INCORRECT = 400;
const ERROR_CODE_AUTHENTICATION = 401;

module.exports = {
  ERROR_CODE, ERROR_CODE_UNDEFINED, ERROR_CODE_INCORRECT, ERROR_CODE_AUTHENTICATION,
};
